- name: Upload the custom Ubuntu ISO to the vSphere datastore and create virtual Machines
  hosts: all
  vars_files:
    - ./vars/variables.yml
    - ./vars/VMs.yml
  tasks:
  - name:  Clone a virtual machine from Linux template and customize
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ DataCenter }}"
      state: "{{item.state}}"
      folder: /Automation/vm
      template: New Virtual Machine
      datastore: "{{Datastore}}"
      disk:
      - size_gb: 17
        type: thin
        datastore: "{{Datastore}}"
      hardware:
        memory_mb: "{{item.memory_mb}}"
        num_cpus: "{{item.num_cpus}}"
        num_cpu_cores_per_socket: "{{item.num_cpu_cores_per_socket}}"
        scsi: "{{item.scsi}}"
        #memory_reservation_lock: True
        #mem_limit: 1024
        #mem_reservation: 1024
        # cpu_limit: 8096
        #cpu_reservation: 4096
        #max_connections: 5
        # hotadd_cpu: True
        #hotremove_cpu: True
        #hotadd_memory: False
        #boot_firmware: "efi"
      name: "{{item.name}}"
      esxi_hostname: "{{item.esxi_hostname}}"
      networks:
      - name: "{{item.Network_name}}"
        ip: "{{item.ip}}"
        netmask: 255.255.255.0
        wait_for_ip_address: yes
        datastore: "{{item.Datastore}}"
    delegate_to: localhost
    loop: "{{vm}}" 
