---
- name: Set password for the Ubuntu user
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ UbuntuVMName }}"
    vm_username: "{{ UbuntuOSUser }}"
    vm_password: VMware1!
    vm_shell: /usr/bin/echo
    vm_shell_args: "'{{ UbuntuOSUser }}:{{ UbuntuOSPassword }}' | sudo chpasswd"
  delegate_to: localhost
   
